// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfhPo9Djcm-_9OeN8lyFTGrSQnuWAFN7I',
    appId: '1:27153655184:web:d2b280a1cc709ce5357f15',
    messagingSenderId: '27153655184',
    projectId: 'ecommerce-project-8aefe',
    authDomain: 'ecommerce-project-8aefe.firebaseapp.com',
    storageBucket: 'ecommerce-project-8aefe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWyiMJyd-Yji1YKidGcgIEA_cVB78jVec',
    appId: '1:27153655184:android:362eae22cf848b89357f15',
    messagingSenderId: '27153655184',
    projectId: 'ecommerce-project-8aefe',
    storageBucket: 'ecommerce-project-8aefe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7gBwFQwZw2pcoU_JO-DfL-N9VhXSZvjA',
    appId: '1:27153655184:ios:fd826d3c7d6c32bc357f15',
    messagingSenderId: '27153655184',
    projectId: 'ecommerce-project-8aefe',
    storageBucket: 'ecommerce-project-8aefe.firebasestorage.app',
    iosBundleId: 'com.example.maheenFlutterPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7gBwFQwZw2pcoU_JO-DfL-N9VhXSZvjA',
    appId: '1:27153655184:ios:fd826d3c7d6c32bc357f15',
    messagingSenderId: '27153655184',
    projectId: 'ecommerce-project-8aefe',
    storageBucket: 'ecommerce-project-8aefe.firebasestorage.app',
    iosBundleId: 'com.example.maheenFlutterPractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfhPo9Djcm-_9OeN8lyFTGrSQnuWAFN7I',
    appId: '1:27153655184:web:31daee648b78f4f4357f15',
    messagingSenderId: '27153655184',
    projectId: 'ecommerce-project-8aefe',
    authDomain: 'ecommerce-project-8aefe.firebaseapp.com',
    storageBucket: 'ecommerce-project-8aefe.firebasestorage.app',
  );
}
